Update pr-policy.yaml

diff --git a/.github/workflows/pr-policy.yaml b/.github/workflows/pr-policy.yaml
--- a/.github/workflows/pr-policy.yaml
+++ b/.github/workflows/pr-policy.yaml
@@ -14,11 +14,17 @@ jobs:
 
       - name: Check Branch Names
         run: |
-          BRANCH_NAME=$(echo "Your current branch is ${{github.base_ref}} compare with ${{github.head_ref}}, applying rules...")
-          if [[ ! "$BRANCH_NAME" =~ ^(feat|fix|rls[0-9]+\.[0-9]+)\/]];
+          echo "Your target branch is "${{github.base_ref}}", applying rules for branch ${{github.head_ref}}, Wait..."
+          if [[ "${{github.base_ref}}" =~ "dvp" && ! "${{github.head_ref}}" =~ ^(feat|fix)\/]];
           then echo "ERROR: Branch name must start with 'feat/', 'fix/', rls#.#/feat or rls#.#/fix" --> Exiting..."
-            exit 1
+          exit 1
+          
+          if [[ "${{github.base_ref}}" =~ "release/rls*" ]];
+          if [[ ! "${{github.head_ref}}" =~ ^(rls[0-9]+\.[0-9]+)\/]];
+          then echo "ERROR: Branch name must start with 'feat/', 'fix/', rls#.#/feat or rls#.#/fix" --> Exiting..."
+          exit 1
           fi
+        #(rls[0-9]+\.[0-9]+)\/
 
   Linting-Codes:
     runs-on: ubuntu-latest
