Update pr-policy.yaml

diff --git a/.github/workflows/pr-policy.yaml b/.github/workflows/pr-policy.yaml
--- a/.github/workflows/pr-policy.yaml
+++ b/.github/workflows/pr-policy.yaml
@@ -1,4 +1,5 @@
-name: Check Branches
+
+name: Build and Deploy
 "on":
   pull_request:
     branches:
@@ -10,19 +11,27 @@ jobs:
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v2
-        
+
       - name: Check Branch Names  - dvp
-        env: 
-            FULL_BRANCH_NAME_DVP: ${{ format('{0}/{1}', github.base_ref, github.head_ref) }}
+        env:
+          FULL_BRANCH_NAME_DVP: ${{ format('{0}/{1}', github.base_ref, github.head_ref) }}
         if: ${{ (github.base_ref == 'dvp') && !contains(env.FULL_BRANCH_NAME_DVP,'dvp/feat/') && !contains(env.FULL_BRANCH_NAME_DVP,'dvp/fix/')  }}
         run: |
-             echo "ERROR⛔: Branch name ( ${{github.head_ref}} ) must start with 'feat/' or 'fix/' --> Exiting..."
-             exit 1
-             
+          echo "ERROR⛔: Branch name ( ${{github.head_ref}} ) must start with 'feat/' or 'fix/' --> Exiting..."
+          exit 1
+
       - name: Check Branch Names - release/rls#.#
-        env: 
+        env:
           FULL_BRANCH_NAME_RLS: ${{ format('{0}/{1}', github.base_ref, github.head_ref) }}
         if: ${{ (github.base_ref != 'dvp') && !contains(env.FULL_BRANCH_NAME_RLS,'rls\d+\.\d+\/feat\/') && !contains(env.FULL_BRANCH_NAME_RLS,'rls\\d+\\.\\d+\\/fix\/')  }}
         run: |
-             echo "ERROR⛔: Branch name  ( ${{github.head_ref}} ) must start with 'rls#.#/feat/' or 'rls#.#/fix/' --> Exiting..."
-             exit 1
+          echo "ERROR⛔: Branch name  ( ${{github.head_ref}} ) must start with 'rls#.#/feat/' or 'rls#.#/fix/' --> Exiting..."
+          exit 1
+
+  Release-Package:
+    runs-on: ubuntu-latest
+    if: ${{ startsWith(github.base_ref, 'release/rls') }}
+    steps:
+      - name: Upload to npm registry
+        run: |
+          echo "DEPLOYING... 🚀"
