Update pr-policy.yaml

diff --git a/.github/workflows/pr-policy.yaml b/.github/workflows/pr-policy.yaml
--- a/.github/workflows/pr-policy.yaml
+++ b/.github/workflows/pr-policy.yaml
@@ -11,14 +11,14 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v2
         
-      - name: Check Branch Names - DVP
-        if: ${{github.base_ref == 'dvp' && !startsWith(github.head_ref, 'fix/') ||  github.base_ref == 'dvp' && !startsWith(github.head_ref, 'feat/') }}
+      - name: Check Branch Names - dvp
+        if: ${{(github.base_ref != 'dvp' || !startsWith(github.head_ref, 'fix/')) && (github.base_ref != 'dvp' || !startsWith(github.head_ref, 'feat/')) }}
         run: |
              echo "ERROR⛔: Branch name ( ${{github.head_ref}} ) must start with 'feat/' or 'fix/' --> Exiting..."
              exit 1
              
-      - name: Check Branch Names - release/rls#.#
-        if: ${{ startsWith(github.base_ref, 'release/rls') && !startsWith(github.head_ref,'rls') || !startsWith(github.head_ref,'rls') && !(contains(github.head_ref, '/feat') || contains(github.head_ref, '/fix'))  }}
-        run: |
-             echo "ERROR⛔: Branch name  ( ${{github.head_ref}} ) must start with 'rls#.#/feat/' or 'rls#.#/fix/' --> Exiting..."
-             exit 1
+      # - name: Check Branch Names - release/rls#.#
+      #   if: ${{ startsWith(github.base_ref, 'release/rls') && !startsWith(github.head_ref,'rls') || !startsWith(github.head_ref,'rls') && !(contains(github.head_ref, '/feat') || contains(github.head_ref, '/fix'))  }}
+      #   run: |
+      #        echo "ERROR⛔: Branch name  ( ${{github.head_ref}} ) must start with 'rls#.#/feat/' or 'rls#.#/fix/' --> Exiting..."
+      #        exit 1
