Update strategy.yaml

diff --git a/.github/workflows/strategy.yaml b/.github/workflows/strategy.yaml
--- a/.github/workflows/strategy.yaml
+++ b/.github/workflows/strategy.yaml
@@ -16,12 +16,13 @@ jobs:
         uses: actions/checkout@v2
       - name: Check Branch Names
         run: |
-          BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD) if [[ "$BRANCH_NAME" == "dvp" ]];  
-          then if [[ ! "$BRANCH_NAME" =~ ^(feat/|fix/) ]]; 
-          then echo "Error: Branch name for 'dvp' must start with 'feat/' or 'fix/'. Exiting..." exit 1 fi 
-          elif [[ "$BRANCH_NAME" == "rls1.0" ]]; 
-          then if [[ ! "$BRANCH_NAME" =~ ^(rls1.0/feat|rls1.0/fix) ]]; 
-          then echo "Error: Branch name for 'rls1.0' must start with 'rls1.0/feat' or 'rls1.0/fix'. Exiting..." exit 1 fi 
+          echo "Its a test for this step"
+   #       BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD) if [[ "$BRANCH_NAME" == "dvp" ]];  
+    #      then if [[ ! "$BRANCH_NAME" =~ ^(feat/|fix/) ]]; 
+     #     then echo "Error: Branch name for 'dvp' must start with 'feat/' or 'fix/'. Exiting..." exit 1 fi 
+     #     elif [[ "$BRANCH_NAME" == "rls1.0" ]]; 
+     #     then if [[ ! "$BRANCH_NAME" =~ ^(rls1.0/feat|rls1.0/fix) ]]; 
+     #     then echo "Error: Branch name for 'rls1.0' must start with 'rls1.0/feat' or 'rls1.0/fix'. Exiting..." exit 1 fi 
 
         # fi # Check if push is directly to the branches 
         # if [[ "$GITHUB_REF" =~ ^refs/heads/(dvp|rls1.0)$ ]]; 
